In [2]:
!pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [3]:
import os
import matplotlib.pyplot as plt
import joblib # to save our model 
import numpy as np

plt.style.use("fivethirtyeight")

In [5]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4 #10 to the power -4
        self.eta = eta # learning rate
        self.epochs = epochs # iteration
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")

In [6]:
obj = Perceptron(eta = 0.01, epochs = 10)

In [7]:
obj.eta

0.01

In [8]:
obj.epochs

10

In [9]:
obj.weights

array([-1.00657065e-04,  1.37706583e-04,  6.77271285e-05])

In [11]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [12]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [13]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
