In [1]:
!pip install joblib

In [2]:
import os
import matplotlib.pyplot as plt
import joblib #to save our model
import numpy as np

plt.style.use("fivethirtyeight")

In [6]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4 
        # it will create some random number
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def fit(self, X, y):
        self. X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with the bias: \n{X_with_bias}")
        
        

In [9]:
obj = Perceptron(eta = 0.01, epochs = 10)

In [10]:
obj.eta

0.01

In [11]:
obj.epochs

10

In [12]:
obj.weights

array([-5.97962808e-05, -1.63272313e-04, -1.24529527e-04])

In [13]:
X = np.ones((4,2))
y = np.ones((4,1))

In [14]:
obj.fit(X,y)

X with the bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
